### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by algerina** [mutinhiri/Group-Capstone-#21]
We are a group of three students, we set up the kanban board and assigned the card to each of us.
Student A: @mutinhiri 
Student B: @sj1978 
Student C: @algerina 

Project link: 
[https://github.com/mutinhiri/Group-Capstone-/projects/4](url)

**Comment by henatan99** [comment]
Hi team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has the wrong link to the project's page. The exact link to the project's page where I can get the Kanban board is [this one](https://github.com/mutinhiri/Group-Capstone-/projects/4). :pray: 
 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mutinhiri** [comment]
hello @henatan99 thank you for the review, however we cannot submit the project with the link that you suggested in the dashboard as code review requests can only accept pull request links and issues link 

![image](https://user-images.githubusercontent.com/76876422/142984294-76398159-83a5-4de7-b5d6-34eaa036564e.png)

**Comment by sjdev2212** [comment]
invalid request
