### ISSUE TITLE
Capstone setup

### ISSUE THREAD

**Issue by sjdev2212** [mutinhiri/Group-Capstone-#22]
We are a group of three students, we set up the kanban board and assigned the card to each of us.
Student A: @mutinhiri
Student B: @sj1978
Student C: @algerina

Project link:
https://github.com/mutinhiri/Group-Capstone-/projects/4

**Comment by Davidosky007** [comment]
## Hi @sj1978 @algerina @mutinhiri 👋, 

Good job so far! 💪 
* Well done providing team details and link to project ✔️ 
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
* Kindly assign each card to a team member, you should see a circle with the user's avatar on each card. See the example below: 
![image](https://user-images.githubusercontent.com/52497246/143042961-9b1d7648-f59e-442e-ac7c-af9ac97b9120.png)
![image](https://user-images.githubusercontent.com/52497246/143043012-1ddbbe99-c26c-4c09-9aed-8f872cd54683.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mutinhiri** [comment]
We have updated our issue by assigning students to each task and assign all students to group tasks

**Comment by SajjadAhmad14** [comment]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

# Hi all, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏

## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by sjdev2212** [comment]
Done
